[package]
name = "cargo-pkgconfig"
version = "0.1.0"
edition = "2021"
license = "MIT"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
cargo_metadata = "0.14.1"
clap = { version = "3.0.12", features = ["cargo"] }
path-slash = "0.1.4"
